export const FETCH_IMAGES = "FETCH_IMAGES";
export const SEARCH_IMAGES = "SEARCH_IMAGES";
export const SET_IMAGES_SEARCH = "SET_IMAGES_SEARCH";
export const SET_IMAGES_TYPE = "SET_IMAGES_TYPE";
export const SET_IMAGES_CATEGORIE = "SET_IMAGES_CATEGORIE";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const IMAGE_LOADED = "IMAGE_LOADED";
export const API_ERROR = "API_ERROR";
